name: Test Suite

on:
  pull_request:
    branches:
      - main
      - staging
      - develop

jobs:
  hardhat-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Hardhat Tests
        id: testing
        run: |
          npm install --only=dev
          # Run tests and output the results as a comment on the PR
          npx hardhat test | tee test-results.txt
          echo "::set-output name=results::$(cat test-results.txt)"